version: '3.3'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=host.docker.internal
      - DB_USERNAME=casaos
      - DB_PASSWORD=casaos
      - DB_NAME=taekwondo_bogor
      - DB_PORT=5432
    volumes:
      - ./src:/app/src
      - ./uploads:/app/uploads
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge