version: '3.8'

services:
  app:
    build: .
    container_name: taekwondo-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DB_HOST=host.docker.internal
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=taekwondo_pengcab_bogor
      - DB_PORT=5432
    volumes:
      - ./src:/app/src
      - ./uploads:/app/uploads
    depends_on:
      - db
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge 