version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    image: taekwondo-app
    container_name: taekwondo-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DB_HOST=host.docker.internal
      - DB_PORT=5432
      - DB_NAME=taekwondo_db
      - DB_USER=postgres
      - DB_PASS=postgres_password
      - DB_SSL=false
      - SESSION_SECRET=your_session_secret
      - JWT_SECRET=your_jwt_secret
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"

# No postgres service since we're using an existing one

volumes:
  uploads: 