version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    image: taekwondo-app
    container_name: taekwondo-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DB_HOST=host.docker.internal
      - DB_PORT=5432
      - DB_NAME=taekwondo_bogor
      - DB_USER=casaos
      - DB_PASS=casaos
      - DB_SSL=false
      - SESSION_SECRET=xaM78fkcKGx/MdPkAc97FPXSBLOycwA2qyN8brHXZOc=
      - JWT_SECRET=vtODH1N7kW2KJOPWSjyuVLyWpKcBrq9f0/XXtOmF0tc=
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"

# No postgres service since we're using an existing one

volumes:
  uploads: 